### ISSUE TITLE
[Android] The text in Inputs is cut off

### ISSUE THREAD

**Issue by markusguenther** [esbenp/react-native-clean-form#34]
When you use custom themes the text in input fields is maybe larger.
Then it can happen that the text is cut off on the top.

The reason is the bar below the text on android. There is no way to disable the line. You can only hide the line but the padding is still there.

This only occurs when the input has a defined height. Otherwise, the framework arranges everything.

**Comment by kruyvanna** [comment]
![device-2017-09-01-144744](https://user-images.githubusercontent.com/1171793/29960124-8d414716-8f24-11e7-8f41-9897bdaf4489.png)

I need large font size on the input. How can I achieve it?

**Comment by dauane** [comment]
I had the same issue. The line on android in my case needed to be bigger than iOS, as such I fixed by simply increasing the line height.  In your fonts file under or themes folder (if you have one), you can do something similar to this:

const display = {
  fontSize: Fonts.displaySize,
  lineHeight: Platform.OS === 'ios' ? Fonts.displayLineHeight : Fonts.displayLineHeight * 1.25,
  backgroundColor: Colors.transparent
}

Hope it helps.
