### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by manikantag** [esbenp/react-native-clean-form#9]
Hi,

> Styled using styled-components. Easily extendible.

Can you give a example about customising the style? I m not able to get it correct. 

I've tried customing the `Label` to not occupy half of the screen, but 1/3 of it.

```
const Label2 = Label`
  flex: 1
`
const Input2 = Input`
  flex: 2
`

render() {
  return (
    <FormGroup>
      <Label2>First name</Label2>
      <Input2 placeholder="Esben" onChangeText={this.onFirstNameChange} />
    </FormGroup>
  )
}

```

And the forms look different in Android compared to the one seen in the README. Is it expected? for native look?

![image](https://cloud.githubusercontent.com/assets/317299/23023862/7c388872-f47d-11e6-922b-80febc1d3f52.png)

**Comment by manikantag** [comment]
After setting the screen bg color to white, it looks like below:

![image](https://cloud.githubusercontent.com/assets/317299/23024246/50ab2e6a-f47f-11e6-8a31-d4ca6f6bfd97.png)

How to get rid of the line under the input field. It looks ugly and not aligned with the label.

**Comment by joshuapinter** [comment]
I agree with this. One of the main reasons why I came to this library is because of the clean, default styling. Even the name has "clean" in it, but on Android it looks terrible.

![screenshot 2017-03-10 09 16 01](https://cloud.githubusercontent.com/assets/180819/23802961/39f03252-0572-11e7-9200-9b83c0a0187d.png)

Any tips on making this look as good as the screenshots on your README would be great. 

Thanks!

**Comment by manikantag** [comment]
@joshuapinter Set the style to `backgroudColor: '#fff'`

**Comment by joshuapinter** [comment]
@manikantag Still not great, though, is it?

**Comment by thienpow** [comment]
try remove border-radius: ${props => props.theme.FormGroup.borderRadius}; from FormGroup.js
this line crash the Android border, making it unable to show the underline on Android... removing it will allow Android and IOS have same long underline under the input and label.
